#!/bin/bash
#
# Example SLURM job script for ALICE

#SBATCH --job-name=STAR_index
#SBATCH --nodes=2
#SBATCH --tasks-per-node=4
#SBATCH --mem=60gb
#SBATCH --time=10:00:00
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ra500@student.le.ac.uk


# Load the R module
module load R

R --vanilla -s -f count_matrix.R
